### ISSUE TITLE
Failed to prepare database on sqlite

### ISSUE THREAD

**Issue by mpraglowski** [RailsEventStore/rails_event_store#163] opened 2017-11-14 00:09 UTC
Steps to reproduce:

1. upgrade RES from 0.18 to 0.19
2. generate migration of schema to 0.19 by
 `rails generate rails_event_store_active_record:v1_v2_migration`
3. `rake db:migrate`
4. `rake db:reset`

and the result is:
```
$ rake db:reset
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
-- create_table("event_store_events", {:id=>:string, :limit=>36, :force=>:cascade})
rake aborted!
ArgumentError: Index name 'sqlite_autoindex_event_store_events_1' on table 'event_store_events' already exists
...
```

**Comment by paneq** [comment] 2017-11-14 07:32
Tested here and works: https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/spec/v1_v2_schema_migration_spec.rb . Can you provide migration files? Is it just your machine or reproduced on many machines?

**Comment by mpraglowski** [comment] 2017-11-14 08:56
Here log what I've done:
https://gist.github.com/092a0d855fb23524cc5281bfb8bfeaf4

migration file used to generate existing database schema
https://gist.github.com/7cb1318580273bf9fbe11c87315fb9d1

migration file generated by RES 0.19
https://gist.github.com/98bb618a48845ea24372dad37fe96f55

**Comment by mpraglowski** [comment] 2017-11-14 09:01
Also 2nd approach with migration of database schema leads to the same error after `rake db:reset`

Here log: https://gist.github.com/f5d850805e2c7b611341c793cbaebad1

**Comment by mpraglowski** [comment] 2017-11-14 09:02
tested only on my machine but 2 different projects

**Comment by mpraglowski** [comment] 2017-11-14 09:27
and another scenario:

```rails new test-app
cd test-app
# add rails_event_store to Gemfile
bundle install
rails generate rails_event_store_active_record:migration
rake db:migrate
rake db:reset
KABOOM :)
```

all on sqlite:

 ```$ sqlite3 -version
3.20.1 2017-08-24 16:21:36 8d3a7ea6c5690d6b7c3767558f4f01b511c55463e3f9e64506801fe9b74dce3```

**Comment by mpraglowski** [comment] 2017-11-14 13:17
confirmed on another machine (sqlite 3.8.10.2) - the same problem

**Comment by pawelpacana** [comment] 2017-11-16 15:31
Research this topic a bit. Leaving here what I know so far:

~1. SQLite introduced `autoindex` feature in version `3.7.17`. This would create index for primary key automatically.~

> Do not confuse automatic indexes with the internal indexes (having names like "sqlite_autoindex_table_N") that are sometimes created to implement a PRIMARY KEY constraint or UNIQUE constraint. The automatic indexes described here exist only for the duration of a single query, are never persisted to disk, and are only visible to a single database connection. Internal indexes are part of the implementation of PRIMARY KEY and UNIQUE constraints, are long-lasting and persisted to disk, and are visible to all database connections. The term "autoindex" appears in the names of internal indexes for legacy reasons and does not indicate that internal indexes and automatic indexes are related.

2. Rails schema dumper in version `5.0` and above would generate `add_index` statement for `schema.rb` from autogenerated index.
3. `rake db:schema:load` tries to create that index twice -- first time automatically on `create_table` and for the seconf time with `add_index`.


Possible solutions to check:
- ~disable autoindex feature for RES migration or `event_store_events` table if possible and add that index in a predictable way with `add_index`~



Reference:
- http://www.sqlite.org/optoverview.html#autoindex
- https://github.com/jashmenn/activeuuid/issues/55

**Comment by pawelpacana** [comment] 2018-09-21 16:58
I assume `0.18` to `0.19` sqlite migration has a very-limited scope and is not used in production (mostly sample apps).`0.19` feels almost prehistoric now. Closing and putting efforts elsewhere.

**Comment by pawelpacana** [comment] 2018-10-03 22:51
The solution is to explicitly add unique index on primary key for sqlite. That prevents Rails from adding one with autogenerated `sqlite_autoindex_event_store_events_1` name.

Explicit name does not fail like the autogenerated one.

**Comment by pawelpacana** [comment] 2018-10-07 17:46
Confirmed on Rails 5.0.x

**Comment by pawelpacana** [comment] 2018-10-07 17:47
Confirmed on Rails 5.1.x

**Comment by pawelpacana** [comment] 2018-10-07 17:48
Seems to be fixed in Rails 5.2.x

**Comment by pawelpacana** [comment] 2018-10-07 18:09
Not an issue on Rails 4.2.x as we already generate named index there.

**Comment by pawelpacana** [comment] 2018-10-07 20:16
> The solution is to explicitly add unique index on primary key for sqlite

Unfortunately that doesn't work. I must have checked it on Rails 5.2 where it is not needed at all. It seems to be not affecting Rails 4.2 as well.

**Comment by pawelpacana** [comment] 2018-10-07 20:44
I'm out of ideas.

1. It is Rails schema dumper bug and it is now fixed in current Rails release. So unlikely to be an issue for new evaluation apps (where you'd likely use sqlite)

2. The fix in apps on unlucky Rails release is to delete `t.index ["id"], name: "sqlite_autoindex_event_store_events_1", unique: true` entry from `schema.rb`

We could probably document that as installation caveat.

**Closed** 2018-10-31 14:54 UTC
Labels: bug
