### ISSUE TITLE
Could not find generator 'rails_event_store_active_record:migration' - issues with spring

### ISSUE THREAD

**Issue by xero88** [RailsEventStore/rails_event_store#172] opened 2017-11-30 09:42 UTC
Hi,

I'm trying to install the gem. But when I do the migration, I got : 
`bin/rails generate rails_event_store_active_record:migration`

> Could not find generator 'rails_event_store_active_record:migration'

And when I type : 
`bin/rails generate --help`

I found nothing about rails_event_store

**Comment by paneq** [comment] 2017-11-30 09:51
@xero88 Could you show `cat Gemfile | grep event_store` and `cat Gemfile.lock | grep event_store`

**Comment by paneq** [comment] 2017-11-30 09:55
Also, what rails version are you using?

**Comment by xero88** [comment] 2017-11-30 10:00
`cat Gemfile | grep event_store `
> gem 'rails_event_store'

`cat Gemfile.lock | grep event_store `
> rails_event_store (0.20.0)
>       rails_event_store_active_record (= 0.20.0)
>       ruby_event_store (= 0.20.0)
>     rails_event_store_active_record (0.20.0)
>       ruby_event_store (= 0.20.0)
>     ruby_event_store (0.20.0)
>   rails_event_store

I'm using gem 'rails', '~> 5.1.4'

**Comment by paneq** [comment] 2017-11-30 10:12
@xero88 I quickly generated a fresh Rails app and I could not reproduce the issue. For now as a workaround you can copy the migration file into your project: https://github.com/paneq/rails5-with-res/blob/master/db/migrate/20171130110955_create_event_store_events.rb . I need to get back to my work right now :) Have a great day!

**Comment by xero88** [comment] 2017-11-30 10:17
@paneq Ok I will do that, thanks.
Do you want my gem file to investigate ?

**Comment by paneq** [comment] 2017-11-30 10:24
@xero88 sure thing, my guess right now is that it could be `spring` related maybe? maybe `spring stop` could help. But that's a guess.

**Comment by xero88** [comment] 2017-11-30 10:28
@paneq it's that !
So I runned
`spring stop`
and then the migration works!
Thank you, have a nice day

**Comment by paneq** [comment] 2017-11-30 10:47
@xero88 I reopened because we still need to fix it for others somehow by triggering `spring` reload. Thank you for your help.

**Comment by antonpaisov** [comment] 2018-03-14 19:56
@paneq I have tried this on both newly generated projects and on older projects that didn't have RES and I can't reproduce the issue. Even if it's still an issue for somebody, I think it might be spring related and not specific RES. Spring is known to have different issues on different project setups.

There's nothing about spring reload in rails documentation on custom generators either http://guides.rubyonrails.org/generators.html
I suggest we close the issue.

**Closed by antonpaisov** 2018-03-14 19:56 UTC

**Comment by paneq** [comment] 2018-03-14 20:11
* I wanted to keep it open in case it occurs so that the developers can more easily find it
* But I also added `spring stop` to the documentation so if people read carefully they should be fine.

**Comment by pawelpacana** [comment] 2018-03-14 20:12
Finding works both on closed and open issues. Should that be a problem we'll readjust approach in the future.

**Comment by paneq** [comment] 2018-03-14 20:16
Actually the default filter is for open issues only https://www.dropbox.com/s/p8d1lr1ob8wfbah/Screenshot%202018-03-14%2021.15.32.png?dl=0 but I am ok with this decision. 💚 ☮️

**Comment by pawelpacana** [comment] 2018-03-14 20:17
🤖
